ALTER TYPE "WhatsAppProvider" ADD VALUE IF NOT EXISTS 'MOCK_WHATSAPP';
ALTER TYPE "WhatsAppIntegrationStatus" ADD VALUE IF NOT EXISTS 'CONNECTING';
ALTER TYPE "WhatsAppIntegrationStatus" ADD VALUE IF NOT EXISTS 'DEACTIVATED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_CONNECTION_STARTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_CONNECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_NUMBER_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_CONNECTION_ERROR';
