ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_INVITE_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_INVITE_ACCEPTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_ACCOUNT_CREATED_FROM_INVITE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_MEMBER_ACTIVATED_FROM_INVITE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_INVITE_ACCEPTANCE_BLOCKED';

ALTER TABLE "BusinessInvitation"
ADD COLUMN IF NOT EXISTS "acceptedByUserId" TEXT;

CREATE INDEX IF NOT EXISTS "BusinessInvitation_acceptedByUserId_idx"
ON "BusinessInvitation"("acceptedByUserId");
