-- Align appointment core naming and add reschedule audit fields.
ALTER TYPE "AppointmentStatus" RENAME VALUE 'PENDING_CONFIRMATION' TO 'PENDING_BUSINESS_CONFIRMATION';

ALTER TYPE "AppointmentActivityType" RENAME VALUE 'CREATED' TO 'APPOINTMENT_CREATED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'UPDATED' TO 'APPOINTMENT_UPDATED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'RESCHEDULED' TO 'APPOINTMENT_RESCHEDULED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'CANCELLED' TO 'APPOINTMENT_CANCELLED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'COMPLETED' TO 'APPOINTMENT_COMPLETED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'NO_SHOW' TO 'APPOINTMENT_NO_SHOW';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'STAFF_ASSIGNED' TO 'APPOINTMENT_ASSIGNED';
ALTER TYPE "AppointmentActivityType" RENAME VALUE 'STATUS_CHANGED' TO 'APPOINTMENT_STATUS_CHANGED';

ALTER TABLE "Appointment" ADD COLUMN "rescheduledById" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "rescheduledAt" TIMESTAMP(3);

ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_rescheduledById_fkey"
  FOREIGN KEY ("rescheduledById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
