ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_AUTO_CONFIRMED_SAFE_BOOKING' AFTER 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_SAFE_CONFIRMATION_REJECTED' AFTER 'APPOINTMENT_AUTO_CONFIRMED_SAFE_BOOKING';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_HUMAN_CONFIRMATION_REQUIRED' AFTER 'APPOINTMENT_SAFE_CONFIRMATION_REJECTED';

ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_AUTO_CONFIRMED_SAFE_BOOKING' AFTER 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_SAFE_CONFIRMATION_REJECTED' AFTER 'APPOINTMENT_AUTO_CONFIRMED_SAFE_BOOKING';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_HUMAN_CONFIRMATION_REQUIRED' AFTER 'APPOINTMENT_SAFE_CONFIRMATION_REJECTED';
