DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AiTone') THEN
    CREATE TYPE "AiTone" AS ENUM ('PROFESSIONAL', 'FRIENDLY', 'SIMPLE');
  END IF;
END $$;

ALTER TYPE "ConversationStatus" ADD VALUE IF NOT EXISTS 'NEEDS_HUMAN_REVIEW';
ALTER TYPE "AppointmentSource" ADD VALUE IF NOT EXISTS 'AI_CONVERSATION';

ALTER TABLE "Business"
ADD COLUMN IF NOT EXISTS "aiRepliesEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "aiAutoReplyEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "aiHandoffOnLowConfidence" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "aiTone" "AiTone" NOT NULL DEFAULT 'PROFESSIONAL',
ADD COLUMN IF NOT EXISTS "aiMinConfidence" DOUBLE PRECISION;

ALTER TABLE "Conversation"
ADD COLUMN IF NOT EXISTS "needsHumanReview" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "humanReviewReason" TEXT;

ALTER TABLE "AccountUsageRecord"
ADD COLUMN IF NOT EXISTS "aiBlockedUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "aiHumanReviewsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "aiBookingRequestsCreated" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "AiInteractionLog"
ADD COLUMN IF NOT EXISTS "plan" "PlanCode",
ADD COLUMN IF NOT EXISTS "quotaStatus" TEXT,
ADD COLUMN IF NOT EXISTS "replySent" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "whatsappSendFailed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "bookingRequestCreated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "appointmentId" TEXT,
ADD COLUMN IF NOT EXISTS "humanReviewNotificationCreated" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "Conversation_businessId_needsHumanReview_idx"
ON "Conversation"("businessId", "needsHumanReview");

CREATE INDEX IF NOT EXISTS "AiInteractionLog_appointmentId_idx"
ON "AiInteractionLog"("appointmentId");
