ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAD_CLAIMED_BY_STAFF';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONVERSATION_CLAIMED_BY_STAFF';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CLAIMED_BY_STAFF';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AI_HANDOFF_TASK_CLAIMED_BY_STAFF';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WORK_REASSIGNED_BY_MANAGER';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WORK_ASSIGNMENT_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_OPERATIONAL_PROFILE_UPDATED';

ALTER TABLE "BusinessMember"
ADD COLUMN IF NOT EXISTS "positionTitle" TEXT,
ADD COLUMN IF NOT EXISTS "specialties" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "serviceTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "isAiHandoffEligible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "aiHandoffPriority" INTEGER;
