ALTER TYPE "AppointmentHumanConfirmationReason" ADD VALUE 'LOW_AI_CONFIDENCE' AFTER 'AVAILABILITY_CONFLICT';

ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_STAFF_ASSIGNED' AFTER 'APPOINTMENT_ASSIGNED';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED' AFTER 'APPOINTMENT_OUTCOME_REQUIRED';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_STAFF_CONFLICT_DETECTED' AFTER 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED';

ALTER TYPE "BusinessNotificationType" ADD VALUE 'APPOINTMENT_ASSIGNED' AFTER 'APPOINTMENT_OUTCOME_REQUIRED';
ALTER TYPE "BusinessNotificationType" ADD VALUE 'APPOINTMENT_AUTO_CONFIRMED' AFTER 'APPOINTMENT_ASSIGNED';

ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_CONFIRMATION_MODE_UPDATED' AFTER 'APPOINTMENT_OUTCOME_REQUIRED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_STAFF_ASSIGNED' AFTER 'APPOINTMENT_CONFIRMATION_MODE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED' AFTER 'APPOINTMENT_STAFF_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_STAFF_CONFLICT_DETECTED' AFTER 'APPOINTMENT_AUTO_CONFIRMED_STAFF_ASSIGNED';
