ALTER TYPE "AppointmentStatus" ADD VALUE 'NEEDS_OUTCOME_CONFIRMATION' AFTER 'RESCHEDULED';
ALTER TYPE "AppointmentStatus" ADD VALUE 'MISSED' AFTER 'NO_SHOW';

ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_MISSED' AFTER 'APPOINTMENT_NO_SHOW';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_OUTCOME_REQUIRED' AFTER 'APPOINTMENT_CONFIRMATION_REQUIRED';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_RESCHEDULE_LIMIT_REACHED' AFTER 'APPOINTMENT_OUTCOME_REQUIRED';
ALTER TYPE "AppointmentActivityType" ADD VALUE 'APPOINTMENT_RESCHEDULE_BLOCKED_PAST' AFTER 'APPOINTMENT_RESCHEDULE_LIMIT_REACHED';

ALTER TYPE "LeadActivityAction" ADD VALUE 'APPOINTMENT_MISSED' AFTER 'APPOINTMENT_NO_SHOW';

ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_MISSED' AFTER 'APPOINTMENT_NO_SHOW';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_OUTCOME_REQUIRED' AFTER 'APPOINTMENT_NOTIFICATION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_RESCHEDULE_LIMIT_REACHED' AFTER 'APPOINTMENT_OUTCOME_REQUIRED';
ALTER TYPE "AuditAction" ADD VALUE 'APPOINTMENT_RESCHEDULE_BLOCKED_PAST' AFTER 'APPOINTMENT_RESCHEDULE_LIMIT_REACHED';

ALTER TYPE "BusinessNotificationType" ADD VALUE 'APPOINTMENT_OUTCOME_REQUIRED' AFTER 'APPOINTMENT_NEEDS_CONFIRMATION';

ALTER TABLE "Appointment" ADD COLUMN "rescheduleCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Appointment" ADD COLUMN "lastRescheduledAt" TIMESTAMP(3);
ALTER TABLE "Appointment" ADD COLUMN "lastRescheduledById" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "outcomeRequiredAt" TIMESTAMP(3);
ALTER TABLE "Appointment" ADD COLUMN "outcomeConfirmedAt" TIMESTAMP(3);
ALTER TABLE "Appointment" ADD COLUMN "outcomeConfirmedById" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "outcomeNote" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "missedReason" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "noShowReason" TEXT;
ALTER TABLE "Appointment" ADD COLUMN "completedNote" TEXT;

UPDATE "Appointment"
SET
  "rescheduleCount" = CASE WHEN "rescheduledAt" IS NULL THEN 0 ELSE 1 END,
  "lastRescheduledAt" = "rescheduledAt"
WHERE "rescheduleCount" = 0;

ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_lastRescheduledById_fkey"
  FOREIGN KEY ("lastRescheduledById") REFERENCES "BusinessMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_outcomeConfirmedById_fkey"
  FOREIGN KEY ("outcomeConfirmedById") REFERENCES "BusinessMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX "Appointment_businessId_outcomeRequiredAt_idx" ON "Appointment"("businessId", "outcomeRequiredAt");
CREATE INDEX "Appointment_businessId_rescheduleCount_idx" ON "Appointment"("businessId", "rescheduleCount");
