DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserAccountType') THEN
    CREATE TYPE "UserAccountType" AS ENUM ('OWNER_CAPABLE', 'STAFF_ONLY');
  END IF;
END $$;

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_ACCOUNT_TYPE_SET';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_CREATION_BLOCKED_FOR_STAFF_ACCOUNT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STAFF_INVITE_BLOCKED_OWNER_EMAIL';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "accountType" "UserAccountType" NOT NULL DEFAULT 'OWNER_CAPABLE',
ADD COLUMN IF NOT EXISTS "canCreateBusiness" BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS "User_accountType_idx"
ON "User"("accountType");

CREATE INDEX IF NOT EXISTS "User_canCreateBusiness_idx"
ON "User"("canCreateBusiness");
