CREATE TYPE "DemoSetupStatus" AS ENUM ('WAITING_FOR_BUSINESS', 'PROCESSING_WEBSITE', 'READY', 'READY_PARTIAL', 'FAILED');
ALTER TABLE "DemoSession"
  ADD COLUMN "setupStatus" "DemoSetupStatus" NOT NULL DEFAULT 'WAITING_FOR_BUSINESS',
  ADD COLUMN "setupAttemptId" TEXT,
  ADD COLUMN "setupStartedAt" TIMESTAMP(3),
  ADD COLUMN "setupCompletedAt" TIMESTAMP(3),
  ADD COLUMN "demoContext" JSONB;
