ALTER TYPE "LeadActivityAction" ADD VALUE 'MESSAGE_SENT';
ALTER TYPE "LeadActivityAction" ADD VALUE 'MESSAGE_SEND_FAILED';
ALTER TYPE "LeadActivityAction" ADD VALUE 'MESSAGE_RETRY_ATTEMPTED';

ALTER TYPE "AuditAction" ADD VALUE 'WHATSAPP_MESSAGE_SENT';
ALTER TYPE "AuditAction" ADD VALUE 'WHATSAPP_MESSAGE_SEND_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'WHATSAPP_MESSAGE_RETRIED';
